sudo: required
language: python
jdk: openjdk8
services: docker
python: '3.6'
cache: pip
matrix:
  fast_finish: true

before_install:
  # Pull the docker image first so the test doesn't wait for this
  - docker pull czbiohub/rnaseq:dev
  # Fake the tag locally so that the pipeline runs properly
  - docker tag czbiohub/rnaseq:dev nfcore/rnaseq:1.2

install:
  # Install Nextflow
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Install czbiohub/tools
  - pip install nf-core
  # Reset
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests

env:
  - NXF_VER='0.32.0' # Specify a minimum NF version that should be tested and work
  - NXF_VER='' # Plus: get the latest NF version and check that it works

script:
  # Lint the pipeline code
  - "nf-core lint ${TRAVIS_BUILD_DIR}"
  # Run, build reference genome with STAR
  - nextflow run ${TRAVIS_BUILD_DIR} -profile test,docker
  # Run, build reference genome with HISAT2
  - nextflow run ${TRAVIS_BUILD_DIR} -profile test,docker --aligner hisat2
