# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: czbiohub-rnaseq-1.2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anaconda::openjdk=8.0.152 # Needed for FastQC - conda build hangs without this
  - bioconda::fastqc=0.11.8
  - bioconda::star=2.6.1b
  - bioconda::hisat2=2.1.0
  - bioconda::picard=2.18.15
  - bioconda::bioconductor-dupradar=1.10.0
  - conda-forge::r-data.table=1.11.4
  - conda-forge::r-gplots=3.0.1
  - bioconda::bioconductor-edger=3.22.5
  - conda-forge::r-markdown=0.8
  - bioconda::csvtk=0.15.0
  - bioconda::preseq=2.0.3
  - bioconda::rseqc=2.6.4
  - bioconda::samtools=1.9
  - bioconda::stringtie=1.3.4
  - bioconda::gffread=0.9.9
  - bioconda::deeptools=3.1.3
  - bioconda::multiqc=1.6
  - bioconda::htseq=0.11.2
  - bioconda::fastp=0.20.0
